# Generated by Django 5.2.17 on 2026-09-26 10:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Подтверждено"),
                            ("progress", "В процессе"),
                            ("locked", "Заблокировано"),
                        ],
                        max_length=16,
                    ),
                ),
                ("earned_at", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EagleLevel",
            fields=[
                ("code", models.CharField(max_length=12, primary_key=True, serialize=False)),
                ("order", models.PositiveSmallIntegerField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("min_meters", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MeterTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.IntegerField()),
                ("reason", models.CharField(max_length=255)),
                ("protocol", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Ручная операция"), ("result", "Результат")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
