# Generated by Django 5.2.17 on 2026-09-26 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("competitions", "0002_initial"),
        ("ratings", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="athlete",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="users.athleteprofile",
            ),
        ),
        migrations.AddField(
            model_name="metertransaction",
            name="athlete",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meter_transactions",
                to="users.athleteprofile",
            ),
        ),
        migrations.AddField(
            model_name="metertransaction",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_meter_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="metertransaction",
            name="result",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meter_transaction",
                to="competitions.competitionresult",
            ),
        ),
        migrations.AddConstraint(
            model_name="metertransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True), name="meter_amount_nonzero"
            ),
        ),
    ]
