# Generated by Django 5.2.17 on 2026-09-26 13:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("competitions", "0003_competition_created_by_competition_external_platform_and_more"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("title", models.CharField(max_length=160)),
                ("statement", models.TextField()),
                ("max_score", models.PositiveIntegerField(default=100)),
                (
                    "check_type",
                    models.CharField(
                        choices=[("auto", "Автопроверка"), ("manual", "Ручная проверка")],
                        default="auto",
                        max_length=8,
                    ),
                ),
                ("time_limit_ms", models.PositiveIntegerField(default=1000)),
                ("memory_limit_mb", models.PositiveIntegerField(default=256)),
                ("materials_url", models.URLField(blank=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("python", "Python 3.12"), ("text", "Текст или ссылка")],
                        max_length=8,
                    ),
                ),
                ("source", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("running", "Проверяется"),
                            ("judged", "Проверено автоматически"),
                            ("pending_review", "Ждёт проверки"),
                            ("reviewed", "Проверено организатором"),
                            ("failed", "Ошибка проверки"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accepted", "Принято"),
                            ("wrong_answer", "Неверный ответ"),
                            ("time_limit", "Превышено время"),
                            ("memory_limit", "Превышена память"),
                            ("runtime_error", "Ошибка выполнения"),
                            ("compile_error", "Ошибка компиляции"),
                        ],
                        max_length=16,
                    ),
                ),
                ("auto_score", models.PositiveIntegerField(blank=True, null=True)),
                ("manual_score", models.PositiveIntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                ("passed_tests", models.PositiveIntegerField(default=0)),
                ("total_tests", models.PositiveIntegerField(default=0)),
                ("max_time_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("max_memory_kb", models.PositiveIntegerField(blank=True, null=True)),
                ("report", models.JSONField(blank=True, default=list)),
                ("compile_log", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="users.athleteprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="contests.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("input", models.TextField(blank=True)),
                ("expected_output", models.TextField()),
                ("is_sample", models.BooleanField(default=False)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="contests.task",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
