# Generated by Django 5.2.17 on 2026-09-26 10:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("approved", "Одобрена"),
                            ("rejected", "Отклонена"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField()),
                ("registration_ends_at", models.DateTimeField()),
                ("capacity", models.PositiveIntegerField()),
                ("reward_meters", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registration", "Регистрация"),
                            ("upcoming", "Скоро"),
                            ("active", "Идёт"),
                            ("finished", "Завершено"),
                        ],
                        db_index=True,
                        default="registration",
                        max_length=20,
                    ),
                ),
                ("schedule", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="CompetitionResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("place", models.PositiveIntegerField()),
                ("score", models.CharField(max_length=100)),
                ("meters_awarded", models.PositiveIntegerField()),
                ("published_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
