# Generated by Django 5.2.17 on 2026-09-26 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("competitions", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="athlete",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="users.athleteprofile",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="discipline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="competitions",
                to="users.discipline",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="competitions.competition",
            ),
        ),
        migrations.AddField(
            model_name="competitionresult",
            name="athlete",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="results",
                to="users.athleteprofile",
            ),
        ),
        migrations.AddField(
            model_name="competitionresult",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="results",
                to="competitions.competition",
            ),
        ),
        migrations.AddField(
            model_name="competitionresult",
            name="published_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="published_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("athlete", "competition"), name="unique_competition_application"
            ),
        ),
        migrations.AddConstraint(
            model_name="competitionresult",
            constraint=models.UniqueConstraint(
                fields=("athlete", "competition"), name="unique_competition_result"
            ),
        ),
    ]
