# Generated by Django 5.2.17 on 2026-09-26 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_competitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="external_platform",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="competition",
            name="external_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="format",
            field=models.CharField(
                choices=[("offline", "Очное"), ("contest", "Онлайн-контест")],
                db_index=True,
                default="offline",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="rules",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("registration", "Регистрация"),
                    ("upcoming", "Скоро"),
                    ("active", "Идёт"),
                    ("finished", "Завершено"),
                ],
                db_index=True,
                default="registration",
                max_length=20,
            ),
        ),
    ]
