import { BarChart3, ClipboardCheck, MapPin, Medal, Trophy, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { LineChart, MetricCard } from '../../components/features/Stats';
import { PageHeader } from '../../components/layout/PageHeader';
import { Badge, Card, ErrorState, LoadingState } from '../../components/ui/Primitives';
import { useApplications, useAthletes, useCities, useCompetitions, useTransactions } from '../../hooks/useData';

export default function AdminDashboardPage() {
  const athletes = useAthletes(); const competitions = useCompetitions(); const applications = useApplications(); const cities = useCities(); const transactions = useTransactions();
  if (athletes.isError || competitions.isError || applications.isError || cities.isError || transactions.isError) return <ErrorState onRetry={() => { athletes.refetch(); competitions.refetch(); applications.refetch(); cities.refetch(); transactions.refetch(); }}/>;
  if (!athletes.data || !competitions.data || !applications.data || !cities.data || !transactions.data) return <LoadingState/>;
  const pending = applications.data.filter((item) => item.status === 'pending');
  const meters = athletes.data.reduce((sum, item) => sum + item.meters, 0);
  return <><PageHeader eyebrow="EAGLECODE_CORE_OS // CONTROL_CENTER" title="Состояние спортивной экосистемы" description="Центр управления участниками, соревнованиями, результатами и рейтинговыми метрами." actions={<Link className="button button-primary" to="/admin/competitions">+ Создать соревнование</Link>}/><div className="metric-grid metric-grid-6"><MetricCard label="Участники" value="1 284" note="+82 за месяц" icon={UsersRound} progress={76}/><MetricCard label="Соревнования" value={String(competitions.data.length)} note="2 открыто" icon={Trophy} progress={62}/><MetricCard label="Начислено метров" value={`${(meters / 1000).toFixed(1)}K`} note="по демо-реестру" icon={BarChart3} progress={83}/><MetricCard label="Города" value={`${cities.data.length} / 52`} note="активные узлы" icon={MapPin} progress={58}/><MetricCard label="На модерации" value={String(pending.length)} note="нужна проверка" icon={ClipboardCheck} progress={40} tone="gold"/><MetricCard label="Протоколы" value="86" note="опубликовано" icon={Medal} progress={88}/></div><div className="dashboard-grid dashboard-grid-admin"><Card><div className="card-title"><div><p className="eyebrow">SPORT GROWTH MAP // ALTITUDE</p><h2>Динамика спортивной экосистемы</h2></div><Badge tone="primary">LIVE</Badge></div><LineChart title="Динамика спортивной экосистемы"/></Card><Card><div className="card-title"><h3>Оперативная модерация</h3><Link to="/admin/applications" className="text-link">Открыть все →</Link></div>{pending.slice(0, 4).map((entry) => { const athlete = athletes.data.find((item) => item.id === entry.athleteId); const competition = competitions.data.find((item) => item.id === entry.competitionId); return <div className="activity-row" key={entry.id}><span className="avatar avatar-small">{athlete?.avatarInitials}</span><div><strong>{athlete?.fullName}</strong><small>{competition?.title}</small></div><Badge tone="gold">Новая</Badge></div>; })}</Card></div><div className="dashboard-grid dashboard-grid-3"><Card><h3>Последние начисления</h3>{transactions.data.slice(0, 4).map((item) => <div className="stat-row" key={item.id}><span>{athletes.data.find((a) => a.id === item.athleteId)?.fullName}<small>{item.reason}</small></span><strong>+{item.amount} м</strong></div>)}</Card><Card><h3>Активные соревнования</h3>{competitions.data.slice(0, 4).map((item) => <div className="stat-row" key={item.id}><span>{item.title}<small>{item.location}</small></span><Badge tone={item.status === 'registration' ? 'primary' : 'muted'}>{item.status}</Badge></div>)}</Card><Card><h3>Системный аудит</h3><div className="system-health"><span><i className="status-dot"/> Mock API</span><strong>12ms</strong><span><i className="status-dot"/> Storage</span><strong>OK</strong><span><i className="status-dot"/> Rating Engine</span><strong>SYNC</strong></div></Card></div></>;
}

