import { useState, type FormEvent } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Plus, Trophy } from 'lucide-react';
import { CompetitionCard } from '../../components/features/CompetitionCard';
import { PageHeader } from '../../components/layout/PageHeader';
import { Button, Card, ErrorState, Field, Input, LoadingState, Select } from '../../components/ui/Primitives';
import { Overlay } from '../../components/ui/Overlay';
import { useApplications, useCompetitions } from '../../hooks/useData';
import { dataClient } from '../../services/client';
import type { CompetitionInput } from '../../types';

export default function AdminCompetitionsPage() {
  const competitions = useCompetitions(); const applications = useApplications(); const [creating, setCreating] = useState(false); const queryClient = useQueryClient();
  const create = useMutation({ mutationFn: (input: CompetitionInput) => dataClient.createCompetition(input), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['competitions'] }); setCreating(false); } });
  if (competitions.isError || applications.isError) return <ErrorState onRetry={() => { competitions.refetch(); applications.refetch(); }}/>;
  if (!competitions.data || !applications.data) return <LoadingState/>;
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const startsAt = String(form.get('startsAt')); create.mutate({ title: String(form.get('title')), description: String(form.get('description')), discipline: String(form.get('discipline')), location: String(form.get('location')), startsAt, endsAt: startsAt, registrationEndsAt: startsAt, capacity: Number(form.get('capacity')), rewardMeters: Number(form.get('rewardMeters')), status: 'registration', schedule: ['09:00 — регистрация', '10:00 — начало соревнований', '17:00 — награждение'] }); };
  return <><PageHeader eyebrow="SPORTS OPERATIONS // ACTIVE_CYCLE" title="Управление соревнованиями" description="Полный жизненный цикл: публикация, заявки, результаты и начисление метров." actions={<Button onClick={() => setCreating(true)}><Plus/> Создать соревнование</Button>}/><div className="metric-grid"><Card className="summary-tile"><Trophy/><span><small>Всего</small><strong>{competitions.data.length}</strong></span></Card><Card className="summary-tile"><Trophy/><span><small>Открыта регистрация</small><strong>{competitions.data.filter((item) => item.status === 'registration').length}</strong></span></Card><Card className="summary-tile"><Trophy/><span><small>Заявок</small><strong>{applications.data.length}</strong></span></Card></div><div className="card-grid card-grid-2">{competitions.data.map((item) => <CompetitionCard competition={item} key={item.id}/>)}</div><Overlay open={creating} title="Новое соревнование" kind="drawer" onClose={() => setCreating(false)}><form className="form-stack" onSubmit={submit}><Field label="Название" htmlFor="cp-title"><Input id="cp-title" name="title" required/></Field><Field label="Описание" htmlFor="cp-description"><Input id="cp-description" name="description" required/></Field><Field label="Дисциплина" htmlFor="cp-discipline"><Input id="cp-discipline" name="discipline" required/></Field><Field label="Место" htmlFor="cp-location"><Input id="cp-location" name="location" required/></Field><Field label="Дата старта" htmlFor="cp-date"><Input id="cp-date" name="startsAt" type="datetime-local" required/></Field><div className="form-grid"><Field label="Лимит" htmlFor="cp-capacity"><Input id="cp-capacity" name="capacity" type="number" min="1" required/></Field><Field label="Максимум метров" htmlFor="cp-meters"><Input id="cp-meters" name="rewardMeters" type="number" min="1" required/></Field></div><Field label="Статус" htmlFor="cp-status"><Select id="cp-status" disabled><option>Регистрация открыта</option></Select></Field><Button type="submit" busy={create.isPending}>Опубликовать</Button></form></Overlay></>;
}
