import { useState, type FormEvent } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Medal, Plus, Trophy } from 'lucide-react';
import { PageHeader } from '../../components/layout/PageHeader';
import { Badge, Button, Card, Field, Input, LoadingState, Select } from '../../components/ui/Primitives';
import { Overlay } from '../../components/ui/Overlay';
import { useAthletes, useCompetitions, useResults } from '../../hooks/useData';
import { dataClient } from '../../services/client';
import type { ResultInput } from '../../types';

export default function AdminResultsPage() {
  const athletes = useAthletes(); const competitions = useCompetitions(); const results = useResults(); const [open, setOpen] = useState(false); const queryClient = useQueryClient();
  const publish = useMutation({ mutationFn: (input: ResultInput) => dataClient.publishResult(input), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['results'] }); queryClient.invalidateQueries({ queryKey: ['athletes'] }); queryClient.invalidateQueries({ queryKey: ['transactions'] }); setOpen(false); } });
  if (!athletes.data || !competitions.data || !results.data) return <LoadingState/>;
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); publish.mutate({ athleteId: String(form.get('athleteId')), competitionId: String(form.get('competitionId')), place: Number(form.get('place')), score: String(form.get('score')), metersAwarded: Number(form.get('metersAwarded')) }); };
  return <><PageHeader eyebrow="OFFICIAL RESULTS // SHA-256" title="Публикация результатов" description="Фиксация мест, результата и автоматическое начисление рейтинговых метров." actions={<Button onClick={() => setOpen(true)}><Plus/> Ввести результат</Button>}/><div className="metric-grid"><Card className="summary-tile"><Trophy/><span><small>Завершено стартов</small><strong>86</strong></span></Card><Card className="summary-tile"><Medal/><span><small>Опубликовано записей</small><strong>{results.data.length}</strong></span></Card></div><Card><div className="admin-list">{results.data.map((item) => { const athlete = athletes.data.find((entry) => entry.id === item.athleteId); const competition = competitions.data.find((entry) => entry.id === item.competitionId); return <article key={item.id}><span className="result-place">#{item.place}</span><div className="admin-list-main"><h3>{athlete?.fullName}</h3><p>{competition?.title}</p><small>Протокол от {new Date(item.publishedAt).toLocaleDateString('ru-RU')}</small></div><Badge tone="primary">{item.score}</Badge><strong>+{item.metersAwarded} м</strong></article>; })}</div></Card><Overlay open={open} title="Зафиксировать результат" kind="drawer" onClose={() => setOpen(false)}><form className="form-stack" onSubmit={submit}><Field label="Соревнование" htmlFor="result-competition"><Select id="result-competition" name="competitionId" required>{competitions.data.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</Select></Field><Field label="Участник" htmlFor="result-athlete"><Select id="result-athlete" name="athleteId" required>{athletes.data.map((item) => <option key={item.id} value={item.id}>{item.fullName}</option>)}</Select></Field><div className="form-grid"><Field label="Место" htmlFor="result-place"><Input id="result-place" name="place" type="number" min="1" required/></Field><Field label="Результат" htmlFor="result-score"><Input id="result-score" name="score" placeholder="01:18:42" required/></Field></div><Field label="Начислить метров" htmlFor="result-meters"><Input id="result-meters" name="metersAwarded" type="number" min="0" required/></Field><Button type="submit" busy={publish.isPending}>Опубликовать протокол</Button></form></Overlay></>;
}

